import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { listSkills } from './manager.js';
import { getSkillsDir } from '../util/fs.js';

export type ExportFormat = 'cursor' | 'windsurf' | 'merged';

export function exportSkills(projectRoot: string, format: ExportFormat): string {
  const skills = listSkills(projectRoot);

  if (skills.length === 0) {
    throw new Error('No skills found. Create one with: mm skill new <name>');
  }

  const skillContents: { name: string; content: string }[] = [];

  for (const skill of skills) {
    if (!skill.hasSkillMd) continue;
    const content = readFileSync(join(getSkillsDir(projectRoot), skill.name, 'SKILL.md'), 'utf-8');
    skillContents.push({ name: skill.name, content });
  }

  if (skillContents.length === 0) {
    throw new Error('No valid SKILL.md files found.');
  }

  switch (format) {
    case 'cursor':
      return formatCursor(skillContents);
    case 'windsurf':
      return formatWindsurf(skillContents);
    case 'merged':
      return formatMerged(skillContents);
    default:
      throw new Error(`Unknown format: ${format}`);
  }
}

export function getOutputFilename(format: ExportFormat): string {
  switch (format) {
    case 'cursor': return '.cursorrules';
    case 'windsurf': return '.windsurfrules';
    case 'merged': return '.rules';
    default: return '.rules';
  }
}

function formatCursor(skills: { name: string; content: string }[]): string {
  const header = `# Cursor Rules
# Generated by mm-cli from .claude/skills/
# ${skills.length} skill${skills.length !== 1 ? 's' : ''} exported
# Regenerate with: mm skill export --format cursor

`;

  const sections = skills.map(s => {
    // Strip YAML frontmatter for cleaner rules
    const body = stripFrontmatter(s.content);
    return `## Skill: ${s.name}\n\n${body}`;
  });

  return header + sections.join('\n\n---\n\n') + '\n';
}

function formatWindsurf(skills: { name: string; content: string }[]): string {
  const header = `# Windsurf Rules
# Generated by mm-cli from .claude/skills/
# ${skills.length} skill${skills.length !== 1 ? 's' : ''} exported
# Regenerate with: mm skill export --format windsurf

`;

  const sections = skills.map(s => {
    const body = stripFrontmatter(s.content);
    return `## ${s.name}\n\n${body}`;
  });

  return header + sections.join('\n\n---\n\n') + '\n';
}

function formatMerged(skills: { name: string; content: string }[]): string {
  const header = `# AI Context Rules
# Generated by mm-cli from .claude/skills/
# Compatible with: Cursor, Windsurf, and other AI coding tools
# ${skills.length} skill${skills.length !== 1 ? 's' : ''} exported
# Regenerate with: mm skill export --format merged

`;

  const sections = skills.map(s => {
    const body = stripFrontmatter(s.content);
    return `## ${s.name}\n\n${body}`;
  });

  return header + sections.join('\n\n---\n\n') + '\n';
}

function stripFrontmatter(content: string): string {
  if (!content.startsWith('---')) return content;
  const endIdx = content.indexOf('---', 3);
  if (endIdx === -1) return content;
  return content.slice(endIdx + 3).trim();
}
